const data = {
  products: [
    {
      name: "Nikke slim shirt",
      slug: "Nikke-slim-shirt-1",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numRevies: 10,
      description: "high quality shirts",
    },
    {
      name: "Nikke slim shirt",
      slug: "Nikke-slim-shirt-2",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numRevies: 10,
      description: "high quality shirts",
    },
    {
      name: "Nikke slim shirt",
      slug: "Nikke-slim-shirt-3",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numRevies: 10,
      description: "high quality shirts",
    },
    {
      name: "Nikke slim shirt",
      slug: "Nikke-slim-shirt-4",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numRevies: 10,
      description: "high quality shirts",
    },
  ],
};

export default data;
